/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsOrganizationLocationIndexRouteImport } from './routes/sessions/$organization/$location/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsOrganizationLocationIndexRoute =
  SessionsOrganizationLocationIndexRouteImport.update({
    id: '/sessions/$organization/$location/',
    path: '/sessions/$organization/$location/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sessions/$organization/$location': typeof SessionsOrganizationLocationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sessions/$organization/$location': typeof SessionsOrganizationLocationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sessions/$organization/$location/': typeof SessionsOrganizationLocationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sessions/$organization/$location'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sessions/$organization/$location'
  id: '__root__' | '/' | '/sessions/$organization/$location/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionsOrganizationLocationIndexRoute: typeof SessionsOrganizationLocationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$organization/$location/': {
      id: '/sessions/$organization/$location/'
      path: '/sessions/$organization/$location'
      fullPath: '/sessions/$organization/$location'
      preLoaderRoute: typeof SessionsOrganizationLocationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionsOrganizationLocationIndexRoute:
    SessionsOrganizationLocationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
