/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizationRouteRouteImport } from './routes/$organization/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as OrganizationIndexRouteImport } from './routes/$organization/index'
import { Route as OrganizationLocationRouteRouteImport } from './routes/$organization/$location/route'
import { Route as OrganizationLocationIndexRouteImport } from './routes/$organization/$location/index'
import { Route as OrganizationLocationSessionsRouteImport } from './routes/$organization/$location/sessions'
import { Route as OrganizationLocationBookSessionRouteRouteImport } from './routes/$organization/$location/book/$session/route'
import { Route as OrganizationLocationBookSessionOccurrenceRouteImport } from './routes/$organization/$location/book/$session/$occurrence'

const OrganizationRouteRoute = OrganizationRouteRouteImport.update({
  id: '/$organization',
  path: '/$organization',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationRouteRoute,
} as any)
const OrganizationLocationRouteRoute =
  OrganizationLocationRouteRouteImport.update({
    id: '/$location',
    path: '/$location',
    getParentRoute: () => OrganizationRouteRoute,
  } as any)
const OrganizationLocationIndexRoute =
  OrganizationLocationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganizationLocationRouteRoute,
  } as any)
const OrganizationLocationSessionsRoute =
  OrganizationLocationSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => OrganizationLocationRouteRoute,
  } as any)
const OrganizationLocationBookSessionRouteRoute =
  OrganizationLocationBookSessionRouteRouteImport.update({
    id: '/book/$session',
    path: '/book/$session',
    getParentRoute: () => OrganizationLocationRouteRoute,
  } as any)
const OrganizationLocationBookSessionOccurrenceRoute =
  OrganizationLocationBookSessionOccurrenceRouteImport.update({
    id: '/$occurrence',
    path: '/$occurrence',
    getParentRoute: () => OrganizationLocationBookSessionRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$organization': typeof OrganizationRouteRouteWithChildren
  '/$organization/$location': typeof OrganizationLocationRouteRouteWithChildren
  '/$organization/': typeof OrganizationIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/$organization/$location/sessions': typeof OrganizationLocationSessionsRoute
  '/$organization/$location/': typeof OrganizationLocationIndexRoute
  '/$organization/$location/book/$session': typeof OrganizationLocationBookSessionRouteRouteWithChildren
  '/$organization/$location/book/$session/$occurrence': typeof OrganizationLocationBookSessionOccurrenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$organization': typeof OrganizationIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/$organization/$location/sessions': typeof OrganizationLocationSessionsRoute
  '/$organization/$location': typeof OrganizationLocationIndexRoute
  '/$organization/$location/book/$session': typeof OrganizationLocationBookSessionRouteRouteWithChildren
  '/$organization/$location/book/$session/$occurrence': typeof OrganizationLocationBookSessionOccurrenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$organization': typeof OrganizationRouteRouteWithChildren
  '/$organization/$location': typeof OrganizationLocationRouteRouteWithChildren
  '/$organization/': typeof OrganizationIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/$organization/$location/sessions': typeof OrganizationLocationSessionsRoute
  '/$organization/$location/': typeof OrganizationLocationIndexRoute
  '/$organization/$location/book/$session': typeof OrganizationLocationBookSessionRouteRouteWithChildren
  '/$organization/$location/book/$session/$occurrence': typeof OrganizationLocationBookSessionOccurrenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$organization'
    | '/$organization/$location'
    | '/$organization/'
    | '/dashboard'
    | '/$organization/$location/sessions'
    | '/$organization/$location/'
    | '/$organization/$location/book/$session'
    | '/$organization/$location/book/$session/$occurrence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$organization'
    | '/dashboard'
    | '/$organization/$location/sessions'
    | '/$organization/$location'
    | '/$organization/$location/book/$session'
    | '/$organization/$location/book/$session/$occurrence'
  id:
    | '__root__'
    | '/'
    | '/$organization'
    | '/$organization/$location'
    | '/$organization/'
    | '/dashboard/'
    | '/$organization/$location/sessions'
    | '/$organization/$location/'
    | '/$organization/$location/book/$session'
    | '/$organization/$location/book/$session/$occurrence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizationRouteRoute: typeof OrganizationRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$organization': {
      id: '/$organization'
      path: '/$organization'
      fullPath: '/$organization'
      preLoaderRoute: typeof OrganizationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organization/': {
      id: '/$organization/'
      path: '/'
      fullPath: '/$organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof OrganizationRouteRoute
    }
    '/$organization/$location': {
      id: '/$organization/$location'
      path: '/$location'
      fullPath: '/$organization/$location'
      preLoaderRoute: typeof OrganizationLocationRouteRouteImport
      parentRoute: typeof OrganizationRouteRoute
    }
    '/$organization/$location/': {
      id: '/$organization/$location/'
      path: '/'
      fullPath: '/$organization/$location/'
      preLoaderRoute: typeof OrganizationLocationIndexRouteImport
      parentRoute: typeof OrganizationLocationRouteRoute
    }
    '/$organization/$location/sessions': {
      id: '/$organization/$location/sessions'
      path: '/sessions'
      fullPath: '/$organization/$location/sessions'
      preLoaderRoute: typeof OrganizationLocationSessionsRouteImport
      parentRoute: typeof OrganizationLocationRouteRoute
    }
    '/$organization/$location/book/$session': {
      id: '/$organization/$location/book/$session'
      path: '/book/$session'
      fullPath: '/$organization/$location/book/$session'
      preLoaderRoute: typeof OrganizationLocationBookSessionRouteRouteImport
      parentRoute: typeof OrganizationLocationRouteRoute
    }
    '/$organization/$location/book/$session/$occurrence': {
      id: '/$organization/$location/book/$session/$occurrence'
      path: '/$occurrence'
      fullPath: '/$organization/$location/book/$session/$occurrence'
      preLoaderRoute: typeof OrganizationLocationBookSessionOccurrenceRouteImport
      parentRoute: typeof OrganizationLocationBookSessionRouteRoute
    }
  }
}

interface OrganizationLocationBookSessionRouteRouteChildren {
  OrganizationLocationBookSessionOccurrenceRoute: typeof OrganizationLocationBookSessionOccurrenceRoute
}

const OrganizationLocationBookSessionRouteRouteChildren: OrganizationLocationBookSessionRouteRouteChildren =
  {
    OrganizationLocationBookSessionOccurrenceRoute:
      OrganizationLocationBookSessionOccurrenceRoute,
  }

const OrganizationLocationBookSessionRouteRouteWithChildren =
  OrganizationLocationBookSessionRouteRoute._addFileChildren(
    OrganizationLocationBookSessionRouteRouteChildren,
  )

interface OrganizationLocationRouteRouteChildren {
  OrganizationLocationSessionsRoute: typeof OrganizationLocationSessionsRoute
  OrganizationLocationIndexRoute: typeof OrganizationLocationIndexRoute
  OrganizationLocationBookSessionRouteRoute: typeof OrganizationLocationBookSessionRouteRouteWithChildren
}

const OrganizationLocationRouteRouteChildren: OrganizationLocationRouteRouteChildren =
  {
    OrganizationLocationSessionsRoute: OrganizationLocationSessionsRoute,
    OrganizationLocationIndexRoute: OrganizationLocationIndexRoute,
    OrganizationLocationBookSessionRouteRoute:
      OrganizationLocationBookSessionRouteRouteWithChildren,
  }

const OrganizationLocationRouteRouteWithChildren =
  OrganizationLocationRouteRoute._addFileChildren(
    OrganizationLocationRouteRouteChildren,
  )

interface OrganizationRouteRouteChildren {
  OrganizationLocationRouteRoute: typeof OrganizationLocationRouteRouteWithChildren
  OrganizationIndexRoute: typeof OrganizationIndexRoute
}

const OrganizationRouteRouteChildren: OrganizationRouteRouteChildren = {
  OrganizationLocationRouteRoute: OrganizationLocationRouteRouteWithChildren,
  OrganizationIndexRoute: OrganizationIndexRoute,
}

const OrganizationRouteRouteWithChildren =
  OrganizationRouteRoute._addFileChildren(OrganizationRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizationRouteRoute: OrganizationRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
